{% set name = "griottes" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griottes-{{ version }}.tar.gz
  sha256: 16a8119888bd90a1b2d224d6c5860455e51fec4bfd948a252f73add83a3ca631

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - python >=3.8
    - scipy
    - tqdm
    - scikit-image
    - scikit-learn
    - seaborn

test:
  imports:
    - griottes
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BaroudLab/Griottes
  summary: Python program to generate NetworkX graphs from segmented images
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - goanpeca
